// "Suggest a block" with a block generated by the Unlimited Chisel Works
// provider (from the hand-made files of `ucw-test-files.ts`), as a candidate
// and as the source.

import "fake-indexeddb/auto";

import { IDBFactory } from "fake-indexeddb";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import * as modRegistry from "../../mods/registry";
import * as store from "../../mods/store";
import { __setGeneratedVanillaLoaderForTests } from "../../mods/generated/registry";
import {
  __resetGeneratedTextureCacheForTests,
  loadGeneratedBlockRender,
  loadGeneratedBlockSetsWithAppearances,
} from "../../mods/generated/render";
import {
  ID,
  UCW,
  VANILLA,
  loadAll,
} from "../../mods/generated/__tests__/ucw-test-files";
import type { BlockAppearance } from "../../render/block-appearance";
import {
  sourceAppearance,
  suggestBlocks,
  suggestionCandidates,
} from "../suggest-blocks";

const VANILLA_BLOCKS = new Set([
  "minecraft:stone",
  "minecraft:planks",
  "minecraft:wool",
]);

function nudge(appearance: BlockAppearance, by: number): BlockAppearance {
  const [l, a, b] = appearance.oklab;
  return { oklab: [l + by, a, b], fullCube: appearance.fullCube };
}

beforeEach(async () => {
  await store.__resetModStoreForTests();
  modRegistry.__resetLoadedModsForTests();
  globalThis.indexedDB = new IDBFactory();
  __setGeneratedVanillaLoaderForTests(async () => VANILLA);
  __resetGeneratedTextureCacheForTests();
});

afterEach(() => {
  __setGeneratedVanillaLoaderForTests(null);
});

async function ucwAppearance(): Promise<BlockAppearance> {
  const { blocks } = await loadGeneratedBlockRender([ID], "1.12.2");
  const appearance = blocks.get(ID)?.appearance;
  expect(appearance).toBeDefined();
  return appearance!;
}

describe("suggestions with generated blocks", () => {
  it("offers generated blocks with their generated appearance", async () => {
    await loadAll();
    const sets = await loadGeneratedBlockSetsWithAppearances("1.12.2");
    const appearance = await ucwAppearance();
    const candidates = suggestionCandidates({
      vanillaBlocks: VANILLA_BLOCKS,
      vanillaColors: null,
      loadedMods: modRegistry.getSnapshot(),
      modIds: new Set([UCW.modId]),
      versionId: "1.12.2",
      generated: sets,
    });
    const generated = candidates.find((c) => c.id === ID);
    expect(generated).toMatchObject({
      sourceLabel: "Unlimited Chisel Works",
      appearance,
    });
    expect(generated?.displayName).toMatch(/\(.+\)$/);

    // Only when the generating mod is mapped or chosen.
    expect(
      suggestionCandidates({
        vanillaBlocks: VANILLA_BLOCKS,
        vanillaColors: null,
        loadedMods: modRegistry.getSnapshot(),
        modIds: new Set(),
        versionId: "1.12.2",
        generated: sets,
      }).map((c) => c.id),
    ).not.toContain(ID);
  });

  it("generates nothing for another version or without the from mod", async () => {
    await loadAll(false);
    expect(await loadGeneratedBlockSetsWithAppearances("1.12.2")).toEqual([]);
    await loadAll();
    expect(await loadGeneratedBlockSetsWithAppearances("1.20.1")).toEqual([]);
  });

  it("ranks a generated block by its appearance", async () => {
    await loadAll();
    const appearance = await ucwAppearance();
    const sets = await loadGeneratedBlockSetsWithAppearances("1.12.2");
    const vanillaColors = {
      "minecraft:stone": nudge(appearance, 0.3),
      "minecraft:planks": nudge(appearance, -0.05),
      "minecraft:wool": nudge(appearance, 0.2),
    };
    const candidates = suggestionCandidates({
      vanillaBlocks: VANILLA_BLOCKS,
      vanillaColors,
      loadedMods: modRegistry.getSnapshot(),
      modIds: new Set([UCW.modId]),
      versionId: "1.12.2",
      generated: sets,
    });
    const ranked = suggestBlocks({
      source: { id: "othermod:pale_wood", appearance: nudge(appearance, 0.01) },
      candidates,
    });
    expect(ranked.map((c) => c.id)).toEqual([
      ID,
      "minecraft:planks",
      "minecraft:wool",
      "minecraft:stone",
    ]);
  });

  it("suggests replacements for a generated source block", async () => {
    await loadAll();
    const { blocks } = await loadGeneratedBlockRender([ID], "1.12.2");
    const appearance = sourceAppearance(
      ID,
      null,
      modRegistry.getSnapshot(),
      "1.12.2",
      blocks.get(ID),
    );
    expect(appearance).toEqual(blocks.get(ID)?.appearance);
    // Another block's resolution isn't used.
    expect(
      sourceAppearance(
        "unlimitedchiselworks:other",
        null,
        [],
        "1.12.2",
        blocks.get(ID),
      ),
    ).toBeUndefined();

    const vanillaColors = {
      "minecraft:stone": nudge(appearance!, 0.3),
      "minecraft:planks": nudge(appearance!, 0.02),
      "minecraft:wool": nudge(appearance!, -0.1),
    };
    const ranked = suggestBlocks({
      source: { id: ID, appearance },
      candidates: suggestionCandidates({
        vanillaBlocks: VANILLA_BLOCKS,
        vanillaColors,
        loadedMods: [],
        modIds: new Set(),
        versionId: "1.20.1",
      }),
    });
    expect(ranked.map((c) => c.id)).toEqual([
      "minecraft:planks",
      "minecraft:wool",
      "minecraft:stone",
    ]);
  });
});
