import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

import { transformBox } from "../mesh-crop";
import {
  matchShapeRule,
  validateShapePack,
  type Box,
  type ShapePack,
} from "../shape-pack";

// The committed pack generated by `pnpm gen:camo-shapes`.
const PACK: ShapePack = validateShapePack(
  JSON.parse(
    readFileSync(
      path.join(
        __dirname,
        "../../../../../public/camo-shapes/framedblocks.json",
      ),
      "utf-8",
    ),
  ),
);

interface PlacedBox {
  slot: string;
  box: Box;
}

function key({ slot, box }: PlacedBox): string {
  return `${slot} ${box.from.join(",")} ${box.to.join(",")}`;
}

/** The block-frame boxes of a state's pieces, sorted. */
function placedBoxes(id: string, props: Record<string, string>): string[] {
  const rules = PACK.blocks[`framedblocks:${id}`];
  expect(rules, id).toBeDefined();
  const rule = matchShapeRule(rules, props);
  expect(rule, `${id} ${JSON.stringify(props)}`).not.toBeNull();
  return rule!.pieces
    .map((piece) =>
      key({
        slot: piece.slot,
        box: transformBox(piece.select, piece.transform),
      }),
    )
    .sort();
}

const box = (
  slot: string,
  from: [number, number, number],
  to: [number, number, number],
) => key({ slot, box: { from, to } });

describe("framedblocks shape pack", () => {
  it("records its source", () => {
    expect(PACK.source).toMatchObject({
      mod: "framedblocks",
      repository: "https://github.com/XFactHD/FramedBlocks",
      license: "LGPL-3.0",
    });
    expect(PACK.source.commit).toMatch(/^[0-9a-f]{40}$/);
  });

  it("places framed_panel on its facing side", () => {
    expect(placedBoxes("framed_panel", { facing: "east" })).toEqual([
      box("camo", [8, 0, 0], [16, 16, 16]),
    ]);
  });

  it("maps framed_double_panel camo to the facing half", () => {
    expect(placedBoxes("framed_double_panel", { facing: "south" })).toEqual([
      box("camo", [0, 0, 8], [16, 16, 16]),
      box("camo_two", [0, 0, 0], [16, 16, 8]),
    ]);
  });

  it("maps framed_double_slab camo to the bottom half", () => {
    expect(placedBoxes("framed_double_slab", {})).toEqual([
      box("camo", [0, 0, 0], [16, 8, 16]),
      box("camo_two", [0, 8, 0], [16, 16, 16]),
    ]);
  });

  it("builds framed_vertical_stairs from the rotated stairs template", () => {
    expect(
      placedBoxes("framed_vertical_stairs", {
        facing: "north",
        type: "vertical",
      }),
    ).toEqual([
      box("camo", [0, 0, 0], [8, 16, 16]),
      box("camo", [8, 0, 0], [16, 16, 8]),
      box("camo", [8, 0, 8], [8, 16, 16]),
    ]);
  });

  it("maps framed_vertical_double_stairs camo_two to the corner pillar", () => {
    expect(
      placedBoxes("framed_vertical_double_stairs", {
        facing: "north",
        type: "vertical",
      }),
    ).toEqual([
      box("camo", [0, 0, 0], [8, 16, 16]),
      box("camo", [8, 0, 0], [16, 16, 8]),
      box("camo", [8, 0, 8], [8, 16, 16]),
      box("camo_two", [8, 0, 8], [16, 16, 16]),
    ]);
  });

  it("maps framed_double_stairs camo to the stairs and camo_two to the filler", () => {
    expect(
      placedBoxes("framed_double_stairs", {
        facing: "north",
        half: "bottom",
        shape: "straight",
      }),
    ).toEqual([
      box("camo", [0, 0, 0], [16, 8, 16]),
      box("camo", [0, 8, 0], [16, 16, 8]),
      box("camo", [0, 8, 8], [16, 8, 16]),
      box("camo_two", [0, 8, 8], [16, 16, 16]),
    ]);
  });

  const HORIZONTAL = ["north", "east", "south", "west"];
  const STAIRS_SHAPES = [
    "straight",
    "inner_left",
    "inner_right",
    "outer_left",
    "outer_right",
  ];
  const STAIRS_TYPES = [
    "vertical",
    "top_fwd",
    "top_ccw",
    "top_both",
    "bottom_fwd",
    "bottom_ccw",
    "bottom_both",
  ];
  const product = (props: Record<string, string[]>) =>
    Object.entries(props).reduce<Record<string, string>[]>(
      (states, [k, values]) =>
        states.flatMap((s) => values.map((v) => ({ ...s, [k]: v }))),
      [{}],
    );

  const FULL_CUBE_DOUBLES: [string, Record<string, string>[]][] = [
    ["framed_double_slab", [{}]],
    ["framed_double_panel", product({ facing: HORIZONTAL })],
    [
      "framed_double_stairs",
      product({
        facing: HORIZONTAL,
        half: ["bottom", "top"],
        shape: STAIRS_SHAPES,
      }),
    ],
    [
      "framed_vertical_double_stairs",
      product({ facing: HORIZONTAL, type: STAIRS_TYPES }),
    ],
  ];

  it.each(FULL_CUBE_DOUBLES)(
    "%s fills the cube with camo and camo_two, without overlap, in every state",
    (id, states) => {
      for (const props of states) {
        const rule = matchShapeRule(PACK.blocks[`framedblocks:${id}`], props);
        expect(rule, JSON.stringify(props)).not.toBeNull();
        const solids = rule!.pieces
          .map((piece) => ({
            slot: piece.slot,
            box: transformBox(piece.select, piece.transform),
          }))
          .filter(({ box: b }) => [0, 1, 2].every((a) => b.to[a] > b.from[a]));
        // Sample each voxel's centre: exactly one camo slot covers it.
        const bad: string[] = [];
        for (let x = 0.5; x < 16; x++) {
          for (let y = 0.5; y < 16; y++) {
            for (let z = 0.5; z < 16; z++) {
              const p = [x, y, z];
              const slots = new Set(
                solids
                  .filter(({ box: b }) =>
                    [0, 1, 2].every((a) => p[a] > b.from[a] && p[a] < b.to[a]),
                  )
                  .map(({ slot }) => slot),
              );
              if (slots.size !== 1) bad.push(p.join(","));
            }
          }
        }
        expect(bad, JSON.stringify(props)).toEqual([]);
      }
    },
  );
});
