import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  BlockDefinition,
  BlockModel,
  Identifier,
  type TextureAtlasProvider,
} from "deepslate";

import { buildCamoMesh, transformBox } from "../mesh-crop";
import {
  matchShapeRule,
  validateShapePack,
  type Box,
  type ShapePack,
  type ShapePiece,
  type ShapeRule,
} from "../shape-pack";

// The committed pack generated by `pnpm gen:camo-shapes`.
const PACK: ShapePack = validateShapePack(
  JSON.parse(
    readFileSync(
      path.join(
        __dirname,
        "../../../../../public/camo-shapes/framedblocks.json",
      ),
      "utf-8",
    ),
  ),
);

interface PlacedBox {
  slot: string;
  box: Box;
}

function key({ slot, box }: PlacedBox): string {
  return `${slot} ${box.from.join(",")} ${box.to.join(",")}`;
}

/** The block-frame boxes of a state's pieces, sorted. */
function placedBoxes(id: string, props: Record<string, string>): string[] {
  const rules = PACK.blocks[`framedblocks:${id}`];
  expect(rules, id).toBeDefined();
  const rule = matchShapeRule(rules, props);
  expect(rule, `${id} ${JSON.stringify(props)}`).not.toBeNull();
  return rule!.pieces
    .map((piece) =>
      key({
        slot: piece.slot,
        box: transformBox(piece.select, piece.transform),
      }),
    )
    .sort();
}

// A plain full-cube camo mesh, block units.
const ATLAS: TextureAtlasProvider = {
  getTextureAtlas: () => ({ width: 4, height: 4 }) as unknown as ImageData,
  getTextureUV: () => [0, 0, 1, 1],
};
const ALL = { texture: "#all" };
const CUBE_MODEL = BlockModel.fromJson({
  textures: { all: "test:block/all" },
  elements: [
    {
      from: [0, 0, 0],
      to: [16, 16, 16],
      faces: {
        down: ALL,
        up: ALL,
        north: ALL,
        south: ALL,
        west: ALL,
        east: ALL,
      },
    },
  ],
});
const CUBE = BlockDefinition.fromJson({
  variants: { "": { model: "test:block/cube" } },
}).getMesh(
  Identifier.parse("test:cube"),
  {},
  ATLAS,
  { getBlockModel: () => CUBE_MODEL },
  {},
);

/** The mesh a state builds from a full-cube camo in every slot. */
function camoMesh(id: string, props: Record<string, string>) {
  const rule = matchShapeRule(PACK.blocks[`framedblocks:${id}`], props);
  expect(rule, `${id} ${JSON.stringify(props)}`).not.toBeNull();
  return buildCamoMesh(rule!.pieces, () => CUBE, {});
}

/** Bounding box of a state's mesh in model pixels, rounded to 0.01. */
function meshBounds(id: string, props: Record<string, string>): Box {
  const from: [number, number, number] = [Infinity, Infinity, Infinity];
  const to: [number, number, number] = [-Infinity, -Infinity, -Infinity];
  for (const quad of camoMesh(id, props).quads) {
    for (const { pos } of quad.vertices()) {
      [pos.x, pos.y, pos.z].forEach((n, axis) => {
        const px = Math.round(n * 1600) / 100;
        from[axis] = Math.min(from[axis], px);
        to[axis] = Math.max(to[axis], px);
      });
    }
  }
  return { from, to };
}

const box = (
  slot: string,
  from: [number, number, number],
  to: [number, number, number],
) => key({ slot, box: { from, to } });

describe("framedblocks shape pack", () => {
  it("records its source", () => {
    expect(PACK.source).toMatchObject({
      mod: "framedblocks",
      repository: "https://github.com/XFactHD/FramedBlocks",
      license: "LGPL-3.0",
    });
    expect(PACK.source.commit).toMatch(/^[0-9a-f]{40}$/);
  });

  it("places framed_panel on its facing side", () => {
    expect(placedBoxes("framed_panel", { facing: "east" })).toEqual([
      box("camo", [8, 0, 0], [16, 16, 16]),
    ]);
  });

  it("maps framed_double_panel camo to the facing half", () => {
    expect(placedBoxes("framed_double_panel", { facing: "south" })).toEqual([
      box("camo", [0, 0, 8], [16, 16, 16]),
      box("camo_two", [0, 0, 0], [16, 16, 8]),
    ]);
  });

  it("maps framed_double_slab camo to the bottom half", () => {
    expect(placedBoxes("framed_double_slab", {})).toEqual([
      box("camo", [0, 0, 0], [16, 8, 16]),
      box("camo_two", [0, 8, 0], [16, 16, 16]),
    ]);
  });

  it("builds framed_vertical_stairs from the rotated stairs template", () => {
    expect(
      placedBoxes("framed_vertical_stairs", {
        facing: "north",
        type: "vertical",
      }),
    ).toEqual([
      box("camo", [0, 0, 0], [8, 16, 16]),
      box("camo", [8, 0, 0], [16, 16, 8]),
      box("camo", [8, 0, 8], [8, 16, 16]),
    ]);
  });

  it("maps framed_vertical_double_stairs camo_two to the corner pillar", () => {
    expect(
      placedBoxes("framed_vertical_double_stairs", {
        facing: "north",
        type: "vertical",
      }),
    ).toEqual([
      box("camo", [0, 0, 0], [8, 16, 16]),
      box("camo", [8, 0, 0], [16, 16, 8]),
      box("camo", [8, 0, 8], [8, 16, 16]),
      box("camo_two", [8, 0, 8], [16, 16, 16]),
    ]);
  });

  it("maps framed_double_stairs camo to the stairs and camo_two to the filler", () => {
    expect(
      placedBoxes("framed_double_stairs", {
        facing: "north",
        half: "bottom",
        shape: "straight",
      }),
    ).toEqual([
      box("camo", [0, 0, 0], [16, 8, 16]),
      box("camo", [0, 8, 0], [16, 16, 8]),
      box("camo", [0, 8, 8], [16, 8, 16]),
      box("camo_two", [0, 8, 8], [16, 16, 16]),
    ]);
  });

  const HORIZONTAL = ["north", "east", "south", "west"];
  const STAIRS_SHAPES = [
    "straight",
    "inner_left",
    "inner_right",
    "outer_left",
    "outer_right",
  ];
  const STAIRS_TYPES = [
    "vertical",
    "top_fwd",
    "top_ccw",
    "top_both",
    "bottom_fwd",
    "bottom_ccw",
    "bottom_both",
  ];
  const product = (props: Record<string, string[]>) =>
    Object.entries(props).reduce<Record<string, string>[]>(
      (states, [k, values]) =>
        states.flatMap((s) => values.map((v) => ({ ...s, [k]: v }))),
      [{}],
    );

  const FULL_CUBE_DOUBLES: [string, Record<string, string>[]][] = [
    ["framed_double_slab", [{}]],
    ["framed_double_panel", product({ facing: HORIZONTAL })],
    [
      "framed_double_stairs",
      product({
        facing: HORIZONTAL,
        half: ["bottom", "top"],
        shape: STAIRS_SHAPES,
      }),
    ],
    [
      "framed_vertical_double_stairs",
      product({ facing: HORIZONTAL, type: STAIRS_TYPES }),
    ],
  ];

  it.each(FULL_CUBE_DOUBLES)(
    "%s fills the cube with camo and camo_two, without overlap, in every state",
    (id, states) => {
      for (const props of states) {
        const rule = matchShapeRule(PACK.blocks[`framedblocks:${id}`], props);
        expect(rule, JSON.stringify(props)).not.toBeNull();
        const solids = rule!.pieces
          .map((piece) => ({
            slot: piece.slot,
            box: transformBox(piece.select, piece.transform),
          }))
          .filter(({ box: b }) => [0, 1, 2].every((a) => b.to[a] > b.from[a]));
        // Sample each voxel's centre: exactly one camo slot covers it.
        const bad: string[] = [];
        for (let x = 0.5; x < 16; x++) {
          for (let y = 0.5; y < 16; y++) {
            for (let z = 0.5; z < 16; z++) {
              const p = [x, y, z];
              const slots = new Set(
                solids
                  .filter(({ box: b }) =>
                    [0, 1, 2].every((a) => p[a] > b.from[a] && p[a] < b.to[a]),
                  )
                  .map(({ slot }) => slot),
              );
              if (slots.size !== 1) bad.push(p.join(","));
            }
          }
        }
        expect(bad, JSON.stringify(props)).toEqual([]);
      }
    },
  );

  const WALL_SIDES = ["none", "low", "tall"];

  it("resolves every framed_wall state to non-empty pieces", () => {
    const states = product({
      up: ["true", "false"],
      north: WALL_SIDES,
      east: WALL_SIDES,
      south: WALL_SIDES,
      west: WALL_SIDES,
    });
    expect(states).toHaveLength(162);
    for (const props of states) {
      const rule = matchShapeRule(
        PACK.blocks["framedblocks:framed_wall"],
        props,
      );
      expect(rule, JSON.stringify(props)).not.toBeNull();
      expect(rule!.pieces.length, JSON.stringify(props)).toBeGreaterThan(0);
      expect(
        camoMesh("framed_wall", props).quads.length,
        JSON.stringify(props),
      ).toBeGreaterThan(0);
    }
  });

  it.each<[string, Record<string, string>, Box]>([
    [
      "framed_wall",
      { up: "true", north: "none", east: "none", south: "none", west: "none" },
      { from: [4, 0, 4], to: [12, 16, 12] },
    ],
    [
      "framed_wall",
      { up: "false", north: "low", east: "none", south: "low", west: "none" },
      { from: [5, 0, 0], to: [11, 14, 16] },
    ],
    [
      "framed_wall",
      { up: "false", north: "tall", east: "tall", south: "none", west: "none" },
      { from: [5, 0, 0], to: [16, 16, 11] },
    ],
    [
      "framed_pane",
      { north: "false", east: "false", south: "false", west: "false" },
      { from: [7, 0, 7], to: [9, 16, 9] },
    ],
    [
      "framed_bars",
      { north: "true", east: "true", south: "false", west: "false" },
      { from: [7, 0, 0], to: [16, 16, 9] },
    ],
    ["framed_board", { faces: "4" }, { from: [0, 0, 0], to: [16, 16, 1] }],
    ["framed_torch", {}, { from: [7, 0, 7], to: [9, 8, 9] }],
    [
      "framed_lantern",
      { hanging: "true", chain: "camo" },
      { from: [5, 1, 5], to: [11, 16, 11] },
    ],
    [
      "framed_lever",
      { face: "wall", facing: "north" },
      { from: [5, 4, 13], to: [11, 12, 16] },
    ],
    ["framed_flower_pot", {}, { from: [5, 0, 5], to: [11, 6, 11] }],
    [
      "framed_chest",
      { facing: "north", type: "left", state: "closed", latch: "none" },
      { from: [1, 0, 1], to: [16, 14, 15] },
    ],
    [
      "framed_mini_cube",
      { rotation: "0", top: "false" },
      { from: [4, 0, 4], to: [12, 8, 12] },
    ],
  ])("builds %s %j in shape", (id, props, bounds) => {
    expect(meshBounds(id, props)).toEqual(bounds);
  });

  it("drops the tinted glass face of framed_one_way_window", () => {
    const faces = camoMesh("framed_one_way_window", { face: "north" }).quads;
    expect(faces).toHaveLength(5);
    expect(faces.every((q) => q.vertices().some((v) => v.pos.z > 0))).toBe(
      true,
    );
  });

  it("maps framed_adj_double_panel camo away from its facing", () => {
    expect(placedBoxes("framed_adj_double_panel", { facing: "east" })).toEqual([
      box("camo", [0, 0, 0], [8, 16, 16]),
      box("camo_two", [8, 0, 0], [16, 16, 16]),
    ]);
  });

  // Blocks ported from bespoke `*Geometry.java` classes.
  const BESPOKE = [
    "framed_cube",
    "framed_secret_storage",
    "framed_tank",
    "framed_bouncy_cube",
    "framed_redstone_block",
    "framed_target",
    "framed_one_way_window",
    "framed_collapsible_block",
    "framed_collapsible_copycat_block",
    "framed_mini_cube",
    "framed_chest",
    "framed_wall",
    "framed_chain",
    "framed_lightning_rod",
    "framed_pane",
    "framed_bars",
    "framed_board",
    "framed_torch",
    "framed_soul_torch",
    "framed_copper_torch",
    "framed_redstone_torch",
    "framed_wall_torch",
    "framed_soul_wall_torch",
    "framed_copper_wall_torch",
    "framed_redstone_wall_torch",
    "framed_lantern",
    "framed_soul_lantern",
    "framed_copper_lantern",
    "framed_sign",
    "framed_hanging_sign",
    "framed_wall_hanging_sign",
    "framed_lever",
    "framed_flower_pot",
    "framed_item_frame",
    "framed_glowing_item_frame",
    "framed_banner",
    "framed_wall_banner",
    "framed_fancy_rail",
    "framed_fancy_powered_rail",
    "framed_fancy_detector_rail",
    "framed_fancy_activator_rail",
  ];

  it.each(BESPOKE)(
    "builds a finite, non-empty mesh for every %s rule",
    (id) => {
      const rules = PACK.blocks[`framedblocks:${id}`];
      expect(rules, id).toBeDefined();
      for (const rule of rules) {
        const quads = buildCamoMesh(rule.pieces, () => CUBE, {}).quads;
        expect(quads.length, JSON.stringify(rule.when)).toBeGreaterThan(0);
        for (const quad of quads) {
          for (const { pos } of quad.vertices()) {
            expect([pos.x, pos.y, pos.z].every(Number.isFinite)).toBe(true);
          }
        }
      }
    },
  );

  // Slope, slope edge, prism, sloped stairs and rail slope blocks (the
  // per-package ports next to `geometry-specs.ts` and their double blocks)
  // are closed solids: meshed from a
  // full-cube camo, each slot's volume (divergence theorem over the quads)
  // is the same from any origin and equals the shape's volume in blocks.
  // Volumes keyed by `alt_type` differ between the two variants; pyramids'
  // are keyed by `pillar` (`none`, `post` or `pillar`).
  const SLOPE_VOLUMES: Record<string, number | Record<string, number>> = {
    framed_slope: 1 / 2,
    framed_half_slope: 1 / 4,
    framed_vertical_half_slope: 1 / 4,
    framed_corner_slope: 1 / 3,
    framed_inner_corner_slope: 2 / 3,
    framed_prism_corner: 1 / 6,
    framed_inner_prism_corner: 5 / 6,
    framed_threeway_corner: 1 / 4,
    framed_inner_threeway_corner: 3 / 4,
    framed_slope_edge: 1 / 8,
    framed_elevated_slope_edge: 7 / 8,
    framed_corner_slope_edge: { false: 1 / 24, true: 1 / 6 },
    framed_inner_corner_slope_edge: { false: 5 / 24, true: 1 / 12 },
    framed_elevated_corner_slope_edge: 19 / 24,
    framed_elevated_inner_corner_slope_edge: 23 / 24,
    framed_threeway_corner_slope_edge: { false: 1 / 32, true: 7 / 32 },
    framed_inner_threeway_corner_slope_edge: { false: 9 / 32, true: 3 / 32 },
    framed_slope_edge_slab: 3 / 8,
    framed_slope_edge_panel: 3 / 8,
    framed_prism: 1 / 4,
    framed_elevated_inner_prism: 3 / 4,
    framed_sloped_prism: 5 / 24,
    framed_elevated_inner_sloped_prism: 19 / 24,
    framed_sloped_stairs: 3 / 4,
    framed_vertical_sloped_stairs: 3 / 4,
    // The rail is a `block` piece, which doesn't cut the camo.
    framed_rail_slope: 1 / 2,
    framed_powered_rail_slope: 1 / 2,
    framed_detector_rail_slope: 1 / 2,
    framed_activator_rail_slope: 1 / 2,
    framed_slope_panel: 1 / 4,
    framed_extended_slope_panel: 3 / 4,
    framed_compound_slope_panel: 1 / 2,
    framed_flat_slope_panel_corner: 1 / 6,
    framed_flat_inner_slope_panel_corner: 1 / 3,
    framed_flat_ext_slope_panel_corner: 2 / 3,
    framed_flat_ext_inner_slope_panel_corner: 5 / 6,
    framed_slope_slab: 1 / 4,
    framed_elevated_slope_slab: 3 / 4,
    framed_compound_slope_slab: 1 / 2,
    framed_flat_slope_slab_corner: 1 / 6,
    framed_flat_inner_slope_slab_corner: 1 / 3,
    framed_flat_elev_slope_slab_corner: 2 / 3,
    framed_flat_elev_inner_slope_slab_corner: 5 / 6,
    framed_pyramid: { none: 1 / 3, post: 11 / 32, pillar: 5 / 12 },
    framed_pyramid_slab: 1 / 6,
    framed_elevated_pyramid_slab: {
      none: 2 / 3,
      post: 43 / 64,
      pillar: 17 / 24,
    },
    framed_upper_pyramid_slab: { none: 1 / 6, post: 11 / 64, pillar: 5 / 24 },
    framed_small_corner_slope_panel: 1 / 12,
    framed_small_corner_slope_panel_w: 1 / 12,
    framed_large_corner_slope_panel: 1 / 3,
    framed_large_corner_slope_panel_w: 1 / 3,
    framed_small_inner_corner_slope_panel: 1 / 6,
    framed_small_inner_corner_slope_panel_w: 1 / 6,
    framed_large_inner_corner_slope_panel: 5 / 12,
    framed_large_inner_corner_slope_panel_w: 5 / 12,
    framed_ext_corner_slope_panel: 7 / 12,
    framed_ext_corner_slope_panel_w: 7 / 12,
    framed_ext_inner_corner_slope_panel: 11 / 12,
    framed_ext_inner_corner_slope_panel_w: 11 / 12,
    framed_small_prism_corner_slope_panel: 1 / 24,
    framed_small_prism_corner_slope_panel_w: 1 / 24,
    framed_large_prism_corner_slope_panel: 7 / 24,
    framed_large_prism_corner_slope_panel_w: 7 / 24,
    framed_small_inner_prism_corner_slope_panel: 23 / 24,
    framed_small_inner_prism_corner_slope_panel_w: 23 / 24,
    framed_large_inner_prism_corner_slope_panel: 17 / 24,
    framed_large_inner_prism_corner_slope_panel_w: 17 / 24,
  };

  // Double blocks: the total of both slots (each closed on its own).
  const SLOPE_DOUBLE_VOLUMES: Record<string, number | Record<string, number>> =
    {
      framed_double_slope: 1,
      framed_divided_slope: 1 / 2,
      framed_double_half_slope: 1 / 2,
      framed_vertical_double_half_slope: 1 / 2,
      framed_double_corner: 1,
      framed_double_prism_corner: 1,
      framed_double_threeway_corner: 1,
      framed_elevated_double_slope_edge: 1,
      framed_stacked_slope_edge: 7 / 8,
      framed_elev_double_corner_slope_edge: 1,
      framed_elev_double_inner_corner_slope_edge: 1,
      framed_stacked_corner_slope_edge: 19 / 24,
      framed_elevated_inner_double_prism: 1,
      framed_elevated_inner_double_sloped_prism: 1,
      framed_sloped_double_stairs: 1,
      framed_sliced_sloped_stairs_slab: 3 / 4,
      framed_sliced_sloped_stairs_slope: 3 / 4,
      framed_vertical_sloped_double_stairs: 1,
      framed_vertical_sliced_sloped_stairs_panel: 3 / 4,
      framed_vertical_sliced_sloped_stairs_slope: 3 / 4,
      framed_double_slope_panel: 1 / 2,
      framed_inv_double_slope_panel: 1 / 2,
      framed_extended_double_slope_panel: 1,
      framed_stacked_slope_panel: 3 / 4,
      framed_flat_double_slope_panel_corner: 1 / 2,
      framed_flat_inv_double_slope_panel_corner: 1 / 2,
      framed_flat_ext_double_slope_panel_corner: 1,
      framed_flat_ext_inner_double_slope_panel_corner: 1,
      framed_flat_stacked_slope_panel_corner: 2 / 3,
      framed_flat_stacked_inner_slope_panel_corner: 5 / 6,
      framed_double_slope_slab: 1 / 2,
      framed_inv_double_slope_slab: 1 / 2,
      framed_elevated_double_slope_slab: 1,
      framed_stacked_slope_slab: 3 / 4,
      framed_flat_double_slope_slab_corner: 1 / 2,
      framed_flat_inv_double_slope_slab_corner: 1 / 2,
      framed_flat_elev_double_slope_slab_corner: 1,
      framed_flat_elev_inner_double_slope_slab_corner: 1,
      framed_flat_stacked_slope_slab_corner: 2 / 3,
      framed_flat_stacked_inner_slope_slab_corner: 5 / 6,
      framed_stacked_pyramid_slab: {
        none: 2 / 3,
        post: 43 / 64,
        pillar: 17 / 24,
      },
      framed_small_double_corner_slope_panel: 1 / 4,
      framed_small_double_corner_slope_panel_w: 1 / 4,
      framed_large_double_corner_slope_panel: 3 / 4,
      framed_large_double_corner_slope_panel_w: 3 / 4,
      framed_inv_double_corner_slope_panel: 1 / 2,
      framed_inv_double_corner_slope_panel_w: 1 / 2,
      framed_ext_double_corner_slope_panel: 1,
      framed_ext_double_corner_slope_panel_w: 1,
      framed_ext_inner_double_corner_slope_panel: 1,
      framed_ext_inner_double_corner_slope_panel_w: 1,
      framed_stacked_corner_slope_panel: 7 / 12,
      framed_stacked_corner_slope_panel_w: 7 / 12,
      framed_stacked_inner_corner_slope_panel: 11 / 12,
      framed_stacked_inner_corner_slope_panel_w: 11 / 12,
    };

  // States FramedBlocks itself doesn't build as closed solids; the extra
  // quads are hidden in-game, and the port keeps them:
  // - an elevated inner prism with a horizontal facing and a vertical axis
  //   also slopes its full back face (`transformAllQuads`), inside the block;
  // - an elevated inner sloped prism with a horizontal facing and
  //   orientation and `alt_slope` cuts the same slope triangle twice.
  // `framed_stacked_inner_corner_slope_edge` is left out: its stairs part is
  // the templated inner stairs, whose overlapping boxes aren't a closed
  // surface either.
  // - an upper pyramid slab with a horizontal facing and no `alt_slope`
  //   has no full faces, so its back face also takes the slope branch and
  //   builds a second half-pyramid in the back half. The block has no item:
  //   it's only part two of the stacked pyramid slab, where that half sits
  //   inside part one's panel.
  // - a large prism corner slope panel wall with `alt_slope` takes its tilt
  //   origin from the opposite facing (`getRotTiltOrigin(dir, rot,
  //   altSlope)` flips `dir`), so its vertical slope quad is moved out of
  //   the block. Still "closed" (a moved face keeps the sum), but not the
  //   7/24 solid; to be checked in-game.
  const isFramedQuirk = (id: string, props: Record<string, string>) =>
    (id === "framed_large_prism_corner_slope_panel_w" &&
      props.alt_slope !== "false") ||
    ((id === "framed_upper_pyramid_slab" ||
      id === "framed_stacked_pyramid_slab") &&
      /^(north|south|west|east)$/.test(props.facing ?? "") &&
      props.alt_slope !== "true") ||
    (id.startsWith("framed_elevated_inner_") &&
      id.endsWith("_prism") &&
      /^(north|south|west|east)_y$/.test(props.facing_axis ?? "")) ||
    (id.startsWith("framed_elevated_inner_") &&
      id.endsWith("sloped_prism") &&
      props.alt_slope === "true" &&
      /^(north|south|west|east)_(north|south|west|east)$/.test(
        props.facing_dir ?? "",
      ));

  /** The expected volume of a rule, picking its `alt_type` or `pillar` variant. */
  const volumeFor = (
    expected: number | Record<string, number>,
    props: Record<string, string>,
  ): number =>
    typeof expected === "number"
      ? expected
      : "none" in expected
        ? expected[props.pillar ?? "none"]
        : expected[props.alt_type ?? "false"];

  /** Signed volume enclosed by a slot's quads, seen from `origin` (blocks). */
  function enclosedVolume(
    pieces: ShapePiece[],
    origin: [number, number, number],
  ): number {
    let volume = 0;
    for (const quad of buildCamoMesh(pieces, () => CUBE, {}).quads) {
      const [a, b, c, d] = quad
        .vertices()
        .map(({ pos }) => [
          pos.x - origin[0],
          pos.y - origin[1],
          pos.z - origin[2],
        ]);
      for (const [p, q, r] of [
        [a, b, c],
        [a, c, d],
      ]) {
        volume +=
          (p[0] * (q[1] * r[2] - q[2] * r[1]) -
            p[1] * (q[0] * r[2] - q[2] * r[0]) +
            p[2] * (q[0] * r[1] - q[1] * r[0])) /
          6;
      }
    }
    return volume;
  }

  /** The slot's volume, checking the surface is closed. */
  function closedVolume(pieces: ShapePiece[], where: string): number {
    const volume = enclosedVolume(pieces, [0, 0, 0]);
    expect(enclosedVolume(pieces, [3, -2, 5]), where).toBeCloseTo(volume, 4);
    return volume;
  }

  // A rule's conditions by current property name (keys also list legacy
  // names, e.g. `alt_slope|yslope`).
  const ruleProps = (rule: ShapeRule): Record<string, string> =>
    Object.fromEntries(
      Object.entries(rule.when ?? {}).map(([key, value]) => [
        key.split("|")[0],
        value,
      ]),
    );

  const slotPieces = (rule: ShapeRule, slot: string) =>
    rule.pieces.filter((piece) => piece.slot === slot);

  it.each(Object.entries(SLOPE_VOLUMES))(
    "builds every %s rule as a closed solid",
    (id, expected) => {
      const rules = PACK.blocks[`framedblocks:${id}`];
      expect(rules, id).toBeDefined();
      for (const rule of rules) {
        const props = ruleProps(rule);
        if (isFramedQuirk(id, props)) continue;
        const where = `${id} ${JSON.stringify(props)}`;
        const volume = volumeFor(expected, props);
        expect(closedVolume(rule.pieces, where), where).toBeCloseTo(volume, 4);
      }
    },
  );

  it.each(Object.entries(SLOPE_DOUBLE_VOLUMES))(
    "builds both parts of every %s rule as closed solids",
    (id, expected) => {
      const rules = PACK.blocks[`framedblocks:${id}`];
      expect(rules, id).toBeDefined();
      for (const rule of rules) {
        const props = ruleProps(rule);
        if (isFramedQuirk(id, props)) continue;
        const where = `${id} ${JSON.stringify(props)}`;
        const volume = volumeFor(expected, props);
        const total =
          closedVolume(slotPieces(rule, "camo"), `${where} camo`) +
          closedVolume(slotPieces(rule, "camo_two"), `${where} camo_two`);
        expect(total, where).toBeCloseTo(volume, 4);
      }
    },
  );

  it("renders framed_stacked_inner_corner_slope_edge as inner stairs plus an inner corner slope edge", () => {
    const rule = matchShapeRule(
      PACK.blocks["framedblocks:framed_stacked_inner_corner_slope_edge"],
      { facing: "north", type: "horizontal_top_left", alt_slope: "false" },
    )!;
    const stairs = matchShapeRule(PACK.blocks["framedblocks:framed_stairs"], {
      facing: "north",
      half: "top",
      shape: "inner_left",
    })!;
    const edge = matchShapeRule(
      PACK.blocks["framedblocks:framed_inner_corner_slope_edge"],
      {
        facing: "north",
        type: "horizontal_top_left",
        alt_type: "true",
        alt_slope: "false",
      },
    )!;
    expect(slotPieces(rule, "camo")).toEqual(stairs.pieces);
    expect(slotPieces(rule, "camo_two")).toEqual(
      edge.pieces.map((piece) => ({ ...piece, slot: "camo_two" })),
    );
  });

  // Faces of a framed_slope (bottom, facing north) from a full-cube camo:
  // the full back and bottom faces, the two side triangles and the slope
  // from the bottom south edge up to the top north edge.
  it("slopes framed_slope from its back edge down to the front", () => {
    const quads = camoMesh("framed_slope", {
      facing: "north",
      type: "bottom",
      alt_slope: "false",
    }).quads.map((quad) =>
      quad
        .vertices()
        .map(({ pos }) => [pos.x, pos.y, pos.z].map((n) => Math.round(n * 16))),
    );
    expect(quads).toHaveLength(5);
    const slope = quads.find(
      (vs) =>
        vs.some(([, y, z]) => y === 16 && z === 0) &&
        vs.some(([, , z]) => z === 16),
    );
    expect(slope).toBeDefined();
    const heights = new Map(slope!.map(([, y, z]) => [z, y]));
    expect(heights.get(0)).toBe(16);
    expect(heights.get(16)).toBe(0);
  });
});
