// Generates a Minecraft 1.12.2 world function that places every Unlimited
// Chisel Works block the UCW fixture needs, plus a structure block preset to
// SAVE them, so the test schematic is saved by the mods themselves instead of
// being hand-written NBT.
//
//   build/ucw-fixture-functions/
//     data/functions/schematiclab/ucw_fixture.mcfunction
//     README.md (in-game steps)
//
// 1.12.2 has no datapacks; world functions live in
// `<world>/data/functions/<namespace>/<name>.mcfunction`.
//
// Inputs: an asiekierka/UnlimitedChiselWorks checkout (UCW_PATH, else
// ~/projects/UnlimitedChiselWorks or ../UnlimitedChiselWorks), whose bundled
// rule files `ucwdefs/chisel/natura.json` and `environmentalmaterials.json`
// are parsed with the app's own rule parser (`src/lib/mods/generated/ucw/
// rules.ts`, which also holds the `UCWBlockRule` naming port). Layout and
// commands: `scripts/ucw-fixtures/layout.ts`.
//
// Usage:
//   node --experimental-strip-types scripts/generate-ucw-fixture-functions.mts
//   (also wired up as `pnpm gen:ucw-fixture-functions`)

import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { execSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  parseUcwRuleFile,
  ucwBlockId,
  ucwSourceBlock,
  type UcwBlockRule,
} from "../src/lib/mods/generated/ucw/rules.ts";
import {
  fixtureArea,
  fixtureFunction,
  STRUCTURE_BLOCK_POS,
  UCW_FIXTURE_FUNCTION,
  UCW_FIXTURE_NAME,
} from "./ucw-fixtures/layout.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");
const OUT_DIR = join(REPO_ROOT, "build/ucw-fixture-functions");
const HOME = process.env.HOME ?? "";

const UCWDEFS = "src/main/resources/assets/unlimitedchiselworks/ucwdefs";
/** Rule files (below `ucwdefs/`) whose rules the fixture places, in order. */
const RULE_FILES = ["chisel/natura.json", "chisel/environmentalmaterials.json"];

function findCheckout(envVar: string, name: string): string {
  const candidates = [
    process.env[envVar],
    join(HOME, "projects", name),
    resolve(REPO_ROOT, "..", name),
  ].filter((path): path is string => path !== undefined && path !== "");
  const found = candidates.find((path) => existsSync(join(path, UCWDEFS)));
  if (found === undefined) {
    throw new Error(
      `No ${name} checkout found (tried ${candidates.join(", ")}); clone https://github.com/asiekierka/UnlimitedChiselWorks and set ${envVar}`,
    );
  }
  return found;
}

function gitHead(checkout: string): string {
  try {
    return execSync("git rev-parse --short HEAD", { cwd: checkout })
      .toString()
      .trim();
  } catch {
    console.warn(`Couldn't read git HEAD in ${checkout}; recording "unknown"`);
    return "unknown";
  }
}

interface FixtureRule {
  path: string;
  rule: UcwBlockRule;
}

function readRules(checkout: string): FixtureRule[] {
  const rules: FixtureRule[] = [];
  for (const path of RULE_FILES) {
    const file = join(checkout, UCWDEFS, path);
    if (!existsSync(file)) throw new Error(`Missing rule file ${file}`);
    const warnings: string[] = [];
    const parsed = parseUcwRuleFile(
      path,
      JSON.parse(readFileSync(file, "utf8")),
      warnings,
    );
    if (parsed === null || warnings.length > 0) {
      throw new Error(`Couldn't parse ${file}: ${warnings.join("; ")}`);
    }
    rules.push(...parsed.rules.map((rule) => ({ path, rule })));
  }
  return rules;
}

function readme(rules: FixtureRule[], commit: string): string {
  const area = fixtureArea(rules.length);
  const [sx, sy, sz] = area.size;
  const [mx, my, mz] = area.max;
  const [bx, by, bz] = STRUCTURE_BLOCK_POS;
  return [
    `# UCW fixture function (Minecraft 1.12.2)`,
    "",
    `Generated by \`pnpm gen:ucw-fixture-functions\` from Unlimited Chisel Works @ ${commit} (\`ucwdefs/${RULE_FILES.join("`, `ucwdefs/")}\`). It places every block of ${rules.length} UCW rules for every \`from\` meta 0–15 and Chisel variation 0–15, beside the \`from\` block at that meta, and a structure block that saves the area as \`${UCW_FIXTURE_NAME}.nbt\`.`,
    "",
    "## Mods (Forge 1.12.2)",
    "",
    "- Chisel (MC1.12.2-1.0.2.45, the version UCW 0.3.5 builds against) and its dependency CTM",
    "- Unlimited Chisel Works 0.3.5",
    "- Natura (and its dependency Mantle)",
    "- Environmental Materials",
    "",
    "Use the latest 1.12.2 releases of Natura and Environmental Materials and write the exact versions down for the fixtures' documentation.",
    "",
    "## Steps",
    "",
    "1. Create a creative superflat world with cheats on, then quit to the title screen.",
    "2. Copy this folder's `data/functions` folder into the world save, so the function is at `saves/<world>/data/functions/schematiclab/ucw_fixture.mcfunction` (merge with an existing `data` folder).",
    `3. Load the world (or run \`/reload\`), switch to spectator mode (\`/gamemode 3\`) so the placed blocks don't trap you, stand where the area's lowest north-west corner should go and run \`/function ${UCW_FIXTURE_FUNCTION}\`.`,
    `4. The function clears the ${sx}×${sy}×${sz} area (x × y × z) with \`fill … air\`, places the blocks and puts a structure block at \`${bx} ${by} ${bz}\` relative to where you ran it (one block west of the area). Switch back to creative (\`/gamemode 1\`), right-click it and press **SAVE**. 1.12 saves it as \`saves/<world>/structures/${UCW_FIXTURE_NAME}.nbt\`.`,
    `5. Optional, with Litematica: select the corners \`~ ~ ~\` and \`~${mx} ~${my} ~${mz}\` relative to where you ran the function (the structure block is outside), and save the selection as \`${UCW_FIXTURE_NAME}\` (\`.minecraft/schematics/${UCW_FIXTURE_NAME}.litematic\`).`,
    `6. Copy \`${UCW_FIXTURE_NAME}.nbt\` (and \`${UCW_FIXTURE_NAME}.litematic\` if you saved one) into \`src/lib/__tests__/fixtures/\`, and record the mod versions and UCW commit with them.`,
    "",
    "## Failed commands are expected",
    "",
    "The function places every meta 0–15 of each `from` block and variation 0–15 of each UCW block, without knowing which exist:",
    "",
    "- A `setblock` of a UCW block whose `from` meta has no state fails with an unknown-block error, because UCW never registered that id. Its row keeps only the `from` block.",
    "- A `setblock` of a data value the block doesn't use either fails or places another state (1.12 maps the data value through the block's `getStateFromMeta`). Chisel blocks with fewer than 16 variations (e.g. `stonebrick1` has 10) behave this way past their last variation.",
    "- A `from` block at a meta it doesn't use may place its default state; only rows that also hold UCW blocks matter.",
    "",
    "## Layout",
    "",
    "Relative to where the function ran: y = rule (layer), z = `from` meta, x = 0 the `from` block at that meta (`setblock ~ ~ ~ <from id> <meta>`), x = 1..16 the UCW block `unlimitedchiselworks:<through>_<from>_<meta>` at data value (variation) 0–15.",
    "",
    "| y | Rule file | Through | From | UCW id (meta 0) |",
    "| --- | --- | --- | --- | --- |",
    ...rules.map(
      ({ path, rule }, layer) =>
        `| ${layer} | \`${path}\` | \`${ucwSourceBlock(rule.through)}\` | \`${ucwSourceBlock(rule.from)}\` | \`${ucwBlockId(rule, 0)}\` |`,
    ),
    "",
  ].join("\n");
}

function main() {
  const checkout = findCheckout("UCW_PATH", "UnlimitedChiselWorks");
  const commit = gitHead(checkout);
  const rules = readRules(checkout);
  rmSync(OUT_DIR, { recursive: true, force: true });
  const functionDir = join(OUT_DIR, "data/functions/schematiclab");
  mkdirSync(functionDir, { recursive: true });
  writeFileSync(
    join(functionDir, "ucw_fixture.mcfunction"),
    fixtureFunction(
      rules.map(({ rule }) => rule),
      [
        `Generated by pnpm gen:ucw-fixture-functions from Unlimited Chisel Works @ ${commit}.`,
        `Run as /function ${UCW_FIXTURE_FUNCTION} on Forge 1.12.2; see README.md.`,
      ],
    ),
  );
  writeFileSync(join(OUT_DIR, "README.md"), readme(rules, commit));
  console.log(
    `Wrote ${OUT_DIR} (${rules.length} rules from ${checkout} @ ${commit})`,
  );
}

try {
  main();
} catch (err) {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
}
