// Generates, from the camo fixtures in `src/lib/__tests__/fixtures/`:
//
//   src/lib/camo/camo-blocks.generated.ts       every block that holds camo,
//     and the FramedBlocks blocks with a second camo slot (worker-side)
//   src/lib/camo/block-properties.generated.ts  every camo block's state
//     properties (editor-side, for carrying properties over on a swap)
//
// The fixtures are structure files the mods saved in-game (CAMO_FIXTURES.md),
// so every block state in them has the block's full set of property names.
// The values are only the ones the datapacks placed (north and east facings,
// a few layer counts); the app widens them with `completePropertyValues`
// (`src/lib/camo/block-properties.ts`). A FramedBlocks block is a double block
// when its saved block entity has `camo_two`.
//
// Re-run it after re-saving the fixtures for a mod release.
//
// Usage:
//   node --experimental-strip-types scripts/generate-camo-block-states.mts
//   (also wired up as `pnpm gen:camo-block-states`)

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { NbtFile } from "deepslate";
import { format } from "prettier";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "..");
const FIXTURE_DIR = join(REPO_ROOT, "src/lib/__tests__/fixtures");
const BLOCKS_OUT = join(REPO_ROOT, "src/lib/camo/camo-blocks.generated.ts");
const PROPERTIES_OUT = join(
  REPO_ROOT,
  "src/lib/camo/block-properties.generated.ts",
);
const HEADER = [
  "// AUTO-GENERATED by scripts/generate-camo-block-states.mts — do NOT edit by hand.",
  "// Regenerate with: pnpm gen:camo-block-states",
  "//",
];

/**
 * The fixtures the datapacks place (`pnpm gen:camo-fixture-datapacks`). The
 * two older hand-saved samples are left out: their mod versions weren't
 * recorded.
 */
const FIXTURES = [
  "copycats_shapes.nbt",
  "copycats_slopes.nbt",
  "framed_covered_1.nbt",
  "framed_covered_2.nbt",
  "framed_covered_3.nbt",
  "framed_covered_4.nbt",
  "framed_slopes_1.nbt",
  "framed_slopes_2.nbt",
  "framed_slope_slabs_panels_1.nbt",
  "framed_slope_slabs_panels_2.nbt",
];

interface PaletteState {
  Name: string;
  Properties?: Record<string, string>;
}

interface StructureBlock {
  state: number;
  nbt?: Record<string, unknown>;
}

interface Structure {
  palette: PaletteState[];
  blocks: StructureBlock[];
}

function isCamoCapable(id: string): boolean {
  return (
    id.startsWith("framedblocks:") ||
    id.startsWith("copycats:") ||
    id.startsWith("create:copycat_")
  );
}

interface CamoBlockStates {
  properties: Map<string, string[]>;
  doubleCamo: boolean;
}

function main(): Promise<void> {
  const blocks = new Map<string, CamoBlockStates>();
  for (const filename of FIXTURES) {
    const root = NbtFile.read(
      new Uint8Array(readFileSync(join(FIXTURE_DIR, filename))),
    ).root.toSimplifiedJson() as Structure;
    for (const block of root.blocks) {
      if (block.nbt === undefined) continue;
      const { Name, Properties = {} } = root.palette[block.state];
      if (!isCamoCapable(Name)) continue;
      let states = blocks.get(Name);
      if (states === undefined) {
        states = { properties: new Map(), doubleCamo: false };
        blocks.set(Name, states);
      }
      for (const [name, value] of Object.entries(Properties)) {
        const values = states.properties.get(name) ?? [];
        if (!values.includes(value)) values.push(value);
        states.properties.set(name, values);
      }
      if (Object.hasOwn(block.nbt, "camo_two")) states.doubleCamo = true;
    }
  }
  return writeTable(blocks);
}

async function writeTs(path: string, lines: string[]): Promise<void> {
  writeFileSync(
    path,
    await format([...HEADER, ...lines, ""].join("\n"), {
      parser: "typescript",
    }),
  );
  process.stderr.write(`Wrote ${path}\n`);
}

async function writeTable(blocks: Map<string, CamoBlockStates>) {
  const sorted = [...blocks].sort(([a], [b]) => a.localeCompare(b));
  const ids = (list: [string, CamoBlockStates][]) =>
    list.map(([id]) => `${JSON.stringify(id)},`);
  await writeTs(BLOCKS_OUT, [
    "// The blocks that save camo in a block entity, from the camo fixtures.",
    "",
    "export const CAMO_BLOCK_IDS: readonly string[] = [",
    ...ids(sorted),
    "];",
    "",
    "/** FramedBlocks double blocks: they also have a `camo_two` slot. */",
    "export const DOUBLE_CAMO_BLOCK_IDS: readonly string[] = [",
    ...ids(sorted.filter(([, states]) => states.doubleCamo)),
    "];",
  ]);
  await writeTs(PROPERTIES_OUT, [
    "// Block-state properties of every camo block, as saved in the camo fixtures.",
    "// Values are the fixtures' samples: read them through `camoBlockProperties`.",
    "",
    "export const CAMO_BLOCK_PROPERTIES: Readonly<",
    "  Record<string, Readonly<Record<string, readonly string[]>>>",
    "> = {",
    ...sorted.map(([id, states]) => {
      const props = [...states.properties.keys()]
        .sort()
        .map(
          (name) =>
            `${name}: ${JSON.stringify(states.properties.get(name)!.sort())}`,
        );
      return `${JSON.stringify(id)}: { ${props.join(", ")} },`;
    }),
    "};",
  ]);
  process.stderr.write(`${blocks.size} camo blocks\n`);
}

await main();
