// Regenerate src/lib/schemlib/schematic-formats/known-versions.ts from
// minecraft-data's data/pc/common/protocolVersions.json plus a hand-curated
// pre-1.20 tail (minecraft-data's protocolVersions.json doesn't include older
// releases). Re-run whenever minecraft-data is updated.
//
// The script looks for protocolVersions.json in this order:
//   1. CLI arg:  npx tsx scripts/regenerate-known-versions.mts <path>
//   2. Env var:  MINECRAFT_DATA_PROTOCOL_VERSIONS=<path>
//   3. Default:  ../minecraft-data/data/pc/common/protocolVersions.json
//                (sibling checkout next to the schematiclab repo)

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const DEFAULT_PROTOCOL_VERSIONS_PATH = path.resolve(
  REPO_ROOT,
  "../minecraft-data/data/pc/common/protocolVersions.json",
);
const PROTOCOL_VERSIONS_PATH =
  process.argv[2] ??
  process.env.MINECRAFT_DATA_PROTOCOL_VERSIONS ??
  DEFAULT_PROTOCOL_VERSIONS_PATH;
const OUTPUT_PATH = path.resolve(
  __dirname,
  "../src/lib/schemlib/schematic-formats/known-versions.ts",
);

interface Entry {
  minecraftVersion: string;
  dataVersion: number;
  releaseType: string;
}

interface KnownEntry {
  version: string;
  tuple: [number, number, number];
  dataVersion: number;
}

// Hand-curated tail: minecraft-data's protocolVersions.json starts at 1.20.
// Older entries are static — they don't change.
const PRE_1_20: KnownEntry[] = [
  { version: "1.12.2", tuple: [1, 12, 2], dataVersion: 1343 },
  { version: "1.13.1", tuple: [1, 13, 1], dataVersion: 1628 },
  { version: "1.16.2", tuple: [1, 16, 2], dataVersion: 2578 },
  { version: "1.16.5", tuple: [1, 16, 5], dataVersion: 2586 },
  { version: "1.17.1", tuple: [1, 17, 1], dataVersion: 2730 },
  { version: "1.18.2", tuple: [1, 18, 2], dataVersion: 2975 },
  { version: "1.19.4", tuple: [1, 19, 4], dataVersion: 3337 },
];

function parseVersionTuple(v: string): [number, number, number] | null {
  const m = /^(\d+)\.(\d+)(?:\.(\d+))?$/.exec(v);
  if (!m) return null;
  return [Number(m[1]), Number(m[2]), Number(m[3] ?? 0)];
}

function compareTuples(
  a: [number, number, number],
  b: [number, number, number],
): number {
  for (let i = 0; i < 3; i++) if (a[i] !== b[i]) return a[i] - b[i];
  return 0;
}

const raw = JSON.parse(readFileSync(PROTOCOL_VERSIONS_PATH, "utf8")) as Entry[];

const fromMcData: KnownEntry[] = [];
for (const e of raw) {
  if (e.releaseType !== "release") continue;
  const tuple = parseVersionTuple(e.minecraftVersion);
  if (!tuple) continue;
  fromMcData.push({
    version: e.minecraftVersion,
    tuple,
    dataVersion: e.dataVersion,
  });
}

// Merge: PRE_1_20 entries override any duplicate (none expected) so the
// hand-curated values win for those specific versions.
const byVersion = new Map<string, KnownEntry>();
for (const e of fromMcData) byVersion.set(e.version, e);
for (const e of PRE_1_20) byVersion.set(e.version, e);

const sorted = [...byVersion.values()].sort((a, b) =>
  compareTuples(a.tuple, b.tuple),
);

const lines: string[] = [];
lines.push("// AUTO-GENERATED by scripts/regenerate-known-versions.mts.");
lines.push("//");
lines.push(
  "// Source: minecraft-data (data/pc/common/protocolVersions.json) for 1.20+,",
);
lines.push("// hand-curated tail for older releases. Regenerate by running:");
lines.push("//   npx tsx scripts/regenerate-known-versions.mts");
lines.push("//");
lines.push(
  "// The map is keyed by version string (e.g. '1.20.1'). When two MC versions",
);
lines.push(
  "// share a DataVersion (rare), getVersionFromDataVersion returns the first",
);
lines.push(
  "// match by sort order (newest first iteration would prefer later releases,",
);
lines.push(
  "// but ascending iteration is fine for our purposes — duplicates aren't",
);
lines.push("// common in practice).");
lines.push("");
lines.push('import type { MinecraftVersion } from "./version-mapping";');
lines.push("");
lines.push("export const KNOWN_VERSIONS: Record<string, MinecraftVersion> = {");
for (const e of sorted) {
  lines.push(
    `  "${e.version}": { platform: "java", versionNumber: [${e.tuple.join(", ")}], dataVersion: ${e.dataVersion} },`,
  );
}
lines.push("};");
lines.push("");

writeFileSync(OUTPUT_PATH, lines.join("\n"));
console.log(`Wrote ${sorted.length} entries to ${OUTPUT_PATH}`);
console.log(
  `Range: ${sorted[0].version} → ${sorted[sorted.length - 1].version}`,
);
