// AUTO-GENERATED by scripts/regenerate-known-versions.mts.
//
// Source: minecraft-data (data/pc/common/protocolVersions.json) for 1.20+,
// hand-curated tail for older releases. Regenerate by running:
//   npx tsx scripts/regenerate-known-versions.mts
//
// The map is keyed by version string (e.g. '1.20.1'). When two MC versions
// share a DataVersion (rare), getVersionFromDataVersion returns the first
// match by sort order (newest first iteration would prefer later releases,
// but ascending iteration is fine for our purposes — duplicates aren't
// common in practice).

import type { MinecraftVersion } from "./version-mapping";

export const KNOWN_VERSIONS: Record<string, MinecraftVersion> = {
  "1.12.2": { platform: "java", versionNumber: [1, 12, 2], dataVersion: 1343 },
  "1.13.1": { platform: "java", versionNumber: [1, 13, 1], dataVersion: 1628 },
  "1.16.2": { platform: "java", versionNumber: [1, 16, 2], dataVersion: 2578 },
  "1.16.5": { platform: "java", versionNumber: [1, 16, 5], dataVersion: 2586 },
  "1.17.1": { platform: "java", versionNumber: [1, 17, 1], dataVersion: 2730 },
  "1.18.2": { platform: "java", versionNumber: [1, 18, 2], dataVersion: 2975 },
  "1.19.4": { platform: "java", versionNumber: [1, 19, 4], dataVersion: 3337 },
  "1.20": { platform: "java", versionNumber: [1, 20, 0], dataVersion: 3463 },
  "1.20.1": { platform: "java", versionNumber: [1, 20, 1], dataVersion: 3465 },
  "1.20.2": { platform: "java", versionNumber: [1, 20, 2], dataVersion: 3578 },
  "1.20.3": { platform: "java", versionNumber: [1, 20, 3], dataVersion: 3698 },
  "1.20.4": { platform: "java", versionNumber: [1, 20, 4], dataVersion: 3700 },
  "1.20.5": { platform: "java", versionNumber: [1, 20, 5], dataVersion: 3837 },
  "1.20.6": { platform: "java", versionNumber: [1, 20, 6], dataVersion: 3839 },
  "1.21": { platform: "java", versionNumber: [1, 21, 0], dataVersion: 3953 },
  "1.21.1": { platform: "java", versionNumber: [1, 21, 1], dataVersion: 3955 },
  "1.21.2": { platform: "java", versionNumber: [1, 21, 2], dataVersion: 4080 },
  "1.21.3": { platform: "java", versionNumber: [1, 21, 3], dataVersion: 4082 },
  "1.21.4": { platform: "java", versionNumber: [1, 21, 4], dataVersion: 4189 },
  "1.21.5": { platform: "java", versionNumber: [1, 21, 5], dataVersion: 4325 },
  "1.21.6": { platform: "java", versionNumber: [1, 21, 6], dataVersion: 4435 },
  "1.21.7": { platform: "java", versionNumber: [1, 21, 7], dataVersion: 4438 },
  "1.21.8": { platform: "java", versionNumber: [1, 21, 8], dataVersion: 4440 },
  "1.21.9": { platform: "java", versionNumber: [1, 21, 9], dataVersion: 4554 },
  "1.21.10": { platform: "java", versionNumber: [1, 21, 10], dataVersion: 4556 },
  "1.21.11": { platform: "java", versionNumber: [1, 21, 11], dataVersion: 4671 },
  "26.1": { platform: "java", versionNumber: [26, 1, 0], dataVersion: 4786 },
  "26.1.1": { platform: "java", versionNumber: [26, 1, 1], dataVersion: 4788 },
  "26.1.2": { platform: "java", versionNumber: [26, 1, 2], dataVersion: 4790 },
};
